Faoma4/Controllers/BeheerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Faoma4.Controllers
{
    public class BeheerController : Controller
    {
        // GET: Beheer
        public ActionResult Index()
        {
            return View();
        }

        // GET: Login
        public ActionResult AccountBeheer()
        {
            //var vm = new LoginViewModel();
            return View();
        }
    }
}

Faoma4/Controllers/contactensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Faoma4;
using BL;
using DAL;

namespace Faoma4.Controllers
{
    public class contactensController : Controller
    {
        //private FaomaModel db = new FaomaModel();
        ContactenService cs = new ContactenService();
        // GET: contactens
        public ActionResult Index()
        {
            //hier moet een selectie gebeuren, enkel die van het ingelogde account

            //var onbewerkteContactenLijst = db.serveraccount_contacten.ToList();
            //List<serveraccount_contacten> bewerkteContactenLijst = new List<serveraccount_contacten>();

            //foreach (var contact in onbewerkteContactenLijst)
            //{
            //    if (!(contact.serverAccountId == tmpServerAccountsId.tmpServerAccountId))
            //    {

            //    }
            //    else { bewerkteContactenLijst.Add(contact); }
            //}

            //List<contacten> doorTeGevenContacten = new List<contacten>();
            ////db.contacten.ToList();
            //foreach (var bewerktContact in bewerkteContactenLijst)
            //{
            //    long tmp =bewerktContact.contactenId;
            //    foreach (var contact in db.contacten.ToList())
            //    {
            //        if (tmp == contact.id)
            //        {
            //            doorTeGevenContacten.Add(contact);
            //        }
            //    }
                

            //}
            //ContactenService c = new ContactenService();
            List<contacten> doorTeGevenContacten2 = cs.contactsFromThisUser();
           // return View(db.contacten.ToList());
            return View(doorTeGevenContacten2);
        }

        // GET: contactens/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contacten contacten = cs.FindContactWithId (id);
            if (contacten == null)
            {
                return HttpNotFound();
            }
            return View(contacten);
        }

        // GET: contactens/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: contactens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Bedrijfsnaam,E_mail")] contacten contacten)
        {
            if (ModelState.IsValid)
            {
                ContactenService cs = new ContactenService();
                cs.createContact(contacten);
                //db.contacten.Add(contacten);
                //db.SaveChanges();

                //bij toevoegen contact moet ook de colom serveraccount_contacten worden aangevuld
                // http://stackoverflow.com/questions/5212751/how-can-i-get-id-of-inserted-entity-in-entity-framework
                //serveraccount_contacten sc = new serveraccount_contacten();
                //db.Entry(contacten).GetDatabaseValues();
                //long id = contacten.id;
                //sc.contactenId = id;
                //sc.serverAccountId = 3;// hardcoaded, moet eigenlijk aan login hangen
                //zoals hierboven, toegepast
                //sc.serverAccountId = tmpServerAccountsId.tmpServerAccountId;
                //db.serveraccount_contacten.Add(sc);
                //db.SaveChanges();
                ///
                return RedirectToAction("Index");
            }

            return View(contacten);
        }

        // GET: contactens/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contacten contacten = cs.FindContactWithId(id);
            if (contacten == null)
            {
                return HttpNotFound();
            }
            return View(contacten);
        }

        // POST: contactens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Bedrijfsnaam,E_mail")] contacten contacten)
        {
            if (ModelState.IsValid)
            {
                cs.EditContact(contacten);
                //db.Entry(contacten).State = EntityState.Modified;
                //db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contacten);
        }

        // GET: contactens/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contacten contacten = cs.FindContactWithId(id);
            if (contacten == null)
            {
                return HttpNotFound();
            }
            return View(contacten);
        }

        // POST: contactens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            //contacten contacten = db.contacten.Find(id);
            //serveraccount_contacten
            // hier komt een foutmelding, in serverAccount_contacten moet deze ook verwijderd worden
            //db.contact_document()



            // serveraccount_contacten sc = (from x in db.serveraccount_contacten
            //                     where x.contactenId == contacten.id
            //                     select x).FirstOrDefault();

            //db.serveraccount_contacten.Remove(sc);



            //db.contacten.Remove(contacten);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

Faoma4/Views/contactens/Create.cshtml
@model Faoma4.contacten

@{
    ViewBag.Title = "Create";
}

<h2>Voeg contact toe</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>contacten</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Bedrijfsnaam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bedrijfsnaam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bedrijfsnaam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.E_mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.E_mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.E_mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Toevoegen" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar de lijst", "Index") |
    @Html.ActionLink("Terug naar beheer", "AccountBeheer", "Beheer")
</div>







@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Faoma4/Views/contactens/Delete.cshtml
@model Faoma4.contacten

@{
    ViewBag.Title = "Delete";
}

<h2>Verwijder contact</h2>

<h3>Ben je zeker dat je dit contact wil verwijderen?</h3>
<div>
    @*<h4>contacten</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Bedrijfsnaam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bedrijfsnaam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.E_mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.E_mail)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Verwijderen" class="btn btn-default" /> |
            @Html.ActionLink("Terug naar de lijst", "Index")
        </div>
    }
</div>

Faoma4/Views/contactens/Details.cshtml
@model Faoma4.contacten

@{
    ViewBag.Title = "Details";
}



<h2>Details contacten</h2>

<div>
    @if (HttpContext.Current.Request.IsAuthenticated)
    {
    @*<h4>contacten</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Bedrijfsnaam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bedrijfsnaam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.E_mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.E_mail)
        </dd>

    </dl>
    }
</div>
<p>
    @Html.ActionLink("Wijzig", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Terug naar de lijst", "Index")
</p>

Faoma4/Views/contactens/Edit.cshtml
@model Faoma4.contacten

@{
    ViewBag.Title = "Edit";
}

<h2>Wijzig contact</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    

    <div class="form-horizontal">
        @*<h4>contacten</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
     

        <div class="form-group">
            @Html.LabelFor(model => model.Bedrijfsnaam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bedrijfsnaam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bedrijfsnaam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.E_mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.E_mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.E_mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Opslaan" class="btn btn-default" />
            </div>
        </div>
    </div>
        
    }

<div>
    @Html.ActionLink("Terug naar de lijst", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Faoma4/Views/contactens/Index.cshtml
@model IEnumerable<Faoma4.contacten>

@{
    ViewBag.Title = "Index";
}

<h2>Overzicht contacten</h2>

<p>
    @Html.ActionLink("Voeg contact toe", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Bedrijfsnaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.E_mail)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Bedrijfsnaam)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.E_mail)
        </td>
        <td>
            @Html.ActionLink("Wijzig", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Verwijder", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>
<div>
    @Html.ActionLink("Terug naar beheer", "AccountBeheer", "Beheer")

</div>