Faoma4/Controllers/HomeController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Faoma4.DAL;
using Faoma4.Helpers;


namespace Faoma4.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            // we halen het id op van de ingelogde gebruiker

             //var id =System.Web.HttpContext.Current.User.Identity.GetUserId();
            //var id=null;
            if ( (tempId.tmpId  == null) )
            {
                tempId.tmpId  = System.Web.HttpContext.Current.User.Identity.GetUserId();

                //serverAccount sa = new serverAccount
                // als er een ingelogde gebruiker is, ze hier het id in tmpId
                //tempId.tmpId = id;
                // en omdat: serverAccounts.userName= id ; // zie iid hierboven,
                // kunnen we van serverAccount ook het id halen
                ServerAccountServerAaccountsHelper ssah = new ServerAccountServerAaccountsHelper(tempId.tmpId);
                long serverAccountsId =ssah.serverAccountsId();
                // we vullen tmpServerAccountId om het op te kunnen halen als nodig
                tmpServerAccountsId.tmpServerAccountId = serverAccountsId;
            }
            // omgekeerde naamgeving
            if (IsStartup.isStartup == false)
            {
                // uitgezet gebeurd nu door service
                //Mailk.StartAllAccountLoops();
                IsStartup.isStartup = true;
            }
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult AccountBeheer()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Edit(string id)
        {
            return RedirectToAction("Edit", "ServerAccounts",id);

        //    //return View();
      }
        public ActionResult EmailVoorbereiden()
        {
            return View();
        }
    }
}

Faoma4/Controllers/HowtoAboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Faoma4.Controllers
{
    public class HowtoAboutController : Controller
    {
        // GET: HowtoAbout
        public ActionResult Index()
        {
            return View();
        }
        // GET: info
        public ActionResult EmailVoorbereiden()
        {
            return View();
        }
    }
}

Faoma4/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
@*<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>*@
<h2>Hoe werkt het</h2>
<div>
    <h2>Maak een email account</h2>
    <p>Ga naar gmail en maak een account </p>
    <p>Stel het account in zodat applicaties toegang krijgen </p>
     @Html.ActionLink("Account voorbereiden", "EmailVoorbereiden", "HowtoAbout")
</div>
<div>
    <h2>Maak een account op de server</h2>
    <p>Klik in het hoofdscherm op "maak account" en vul de gegevens in</p>
    <p>Download de software</p>
</div>
<div>
    <h2>Installeer de software op je computer</h2>
    <p>Open de software op je computer en installeer ze</p>
    <p>Vul de gegevens in, het grootste deel zal default voorgesteld worden</p>
</div>

@Html.ActionLink("Home", "Index", "Home")

Faoma4/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>